name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install NDK
        run: |
          yes | sdkmanager "ndk;29.0.14206865"

      - name: Set NDK_HOME
        run: |
          echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV

      - name: Verify NDK
        shell: bash
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "NDK_HOME=$NDK_HOME"
          ls -la "$ANDROID_HOME"
          ls -la "$ANDROID_HOME/ndk" || true
          ls -la "$NDK_HOME" || true

      - name: Build libhevtun
        shell: bash
        env:
          NDK_HOME: ${{ env.NDK_HOME }}
        run: |
          chmod +x compile-hevtun.sh
          ./compile-hevtun.sh

      - name: Copy libhevtun
        run: |
          cp -r libs V2rayNG/app

      - name: Download libv2ray
        uses: robinraju/release-downloader@v1
        with:
          repository: 2dust/AndroidLibXrayLite
          latest: true
          fileName: libv2ray.aar
          out-file-path: V2rayNG/app/libs/

      - name: Build APK
        working-directory: V2rayNG
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: List generated APKs
        run: |
          echo "Generated APKs:"
          find V2rayNG/app/build/outputs/apk -name "*.apk"

      - name: Verify APKs
        shell: bash
        run: |
          BUILD_TOOLS=$(find "$ANDROID_HOME/build-tools" -maxdepth 1 -type d | sort -V | tail -n1)
          echo "Using Build Tools: $BUILD_TOOLS"

          for apk in $(find V2rayNG/app/build/outputs/apk -name "*.apk"); do
            echo "======================================="
            echo "APK: $apk"

            echo "ZIP TEST"
            unzip -t "$apk" || true

            echo "APK SIGNATURE"
            "$BUILD_TOOLS/apksigner" verify --verbose --print-certs "$apk" || true
          done

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mah2ray-APK
          path: |
            V2rayNG/app/build/outputs/apk/playstore/**/*.apk
            V2rayNG/app/build/outputs/apk/fdroid/**/*.apk
